name = "backend"
main = "src/index.ts"
compatibility_date = "2025-01-21"

# compatibility_flags = [ "nodejs_compat" ]

 #[vars]
 #MY_VAR = "my-variable"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZjkzYTAzMjQtZWQzMC00ZjRlLTgyNGQtMDE0NmM1Y2M1NmFmIiwidGVuYW50X2lkIjoiMTVjZTI2MDZiMGI0MDdlZTJiMjE5MDkxNDYwODlmNzg4MWJlZWI5MzhlYTBhYjllNDQ0OTZlYWYwNTQ0MTgwNiIsImludGVybmFsX3NlY3JldCI6IjJiM2U3NWNlLWJlZmUtNGQzMS1hNTJjLTUyMTVjNWNiZGJkNiJ9.Ylp2Tc3WnrOYfnkmMqxOVo00kQB7pBGwivybUoipxx8"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1